### ISSUE TITLE
Feature request: Show IMDb score

### ISSUE THREAD

**Issue by Gauvino** [Namo2/InPlayerEpisodePreview#18]
Show the IMDb score in episode preview (and also rotten tomatoes if possible)

**Comment by Namo2** [comment]
I will release a new version in a minute.
Getting the rating from other databases is a bit tricky,
For now, I just added the community rating which Jellyfin uses.
I guess it queries it from some other place (probably the metadata provider for the show)
but I am not sure about that

**Comment by Gauvino** [comment]
First of all thanks for being this fast and the implementation is really cleaned but I have a question, wouldn't it be better to put the information like at the bottom (look at the screenshot below), to have a more compact design?
![q2THNVMQN7](https://github.com/Namo2/InPlayerEpisodePreview/assets/68083474/a296ae5f-5044-4caf-b431-e72a9bb03497)

**Comment by Namo2** [comment]
Right. Maybe I will.
I try to stay as close as possible to the way Jellyfin has implemented things.
Took this section as my reference point from the dashboard of an episode:
![image](https://github.com/Namo2/InPlayerEpisodePreview/assets/48796374/0fb56f86-74c9-44cf-bca0-e391453d507e)

I also plan to add some settings. Maybe this position will be one of them.
If you have any other ideas let me know

**Comment by Gauvino** [comment]
No problem, thanks for all and I will let you know if I have any ideas !

**Comment by Gauvino** [comment]
> @Gauvino btw i have seen, that jellyfin has rotten (and fresh?) tomato ratings for movies. Is this also a thing for shows and a settings issue on my site? If yes i could add those ratings quite easily for the next release

![chrome_aWJrsXq93Y](https://github.com/Namo2/InPlayerEpisodePreview/assets/68083474/9ae7b580-4d66-4212-98b3-e5690d960492)
This all the ratings I have on jellyfin, only imdb and rotten, what is fresh ??

And not every show's as the rottentomatoes, in exemple for me on some anime i don't have the rotten one:
Exemple: 
![chrome_Tnpvqch0bz](https://github.com/Namo2/InPlayerEpisodePreview/assets/68083474/3c03b300-7919-4084-af2b-3f1c694b3273)

And yes, i think it's a good idea to add it !

**Comment by Namo2** [comment]
![image](https://github.com/Namo2/InPlayerEpisodePreview/assets/48796374/1e958a15-666d-433c-9387-90cc3ef619fb)
This is marked as mediaInfoCriticRatingRotten

![image](https://github.com/Namo2/InPlayerEpisodePreview/assets/48796374/afcb77e9-5d31-4a6d-b33f-7c6d7125d850)
While this is marked as mediaInfoCriticRatingFresh

So yeah, i will add both of them, just never saw any of that in the shows i have

**Comment by Namo2** [comment]
Do you have a list or 1-2 suggestions of shows/anime which have this kind of rating?
So I can test it after I make the changes?

**Comment by Gauvino** [comment]
Ok so after investigation, I couldn't find any shows with the rotten score idk why

**Comment by Namo2** [comment]
Well, i could add them anyways, 
so if jellyfin should ever decide to display them for shows, they should be there without any further update
