### ISSUE TITLE
This plugin breaks another plugin (Ani-Sync Jellyfin Plugin).

### ISSUE THREAD

**Issue by XDark187** [Namo2/InPlayerEpisodePreview#22]
As the title says, enabling InPlayerEpisodePreview breaks Ani-Sync completely, so I'll be disabling this plugin until this bug is fixed.
This is the effected plugin: https://github.com/vosmiic/jellyfin-ani-sync

**Comment by Namo2** [comment]
> Ani-Sync lets you synchorinze your Jellyfin Anime watch progress to popular services.

Could you tell me which service you are using exactly? 
So i can recreate the problem in the best way.

**Comment by XDark187** [comment]
I've tried MyAnimeList and Anilist both didn't work, but I don't think it matters since you can reproduce the problem by just enabling both plugins at the same time, and then going to the settings of Ani-Sync you'll notice that all buttons are not working and also the providers dropdown menu will be empty as shown in the image below.

This is with both plugins enabled:
![image](https://github.com/Namo2/InPlayerEpisodePreview/assets/39034192/7f3fc5e8-01eb-459b-8ac8-e7670f641fad)

and this is with InPlayerEpisodePreview disabled: (this is how Ani-Sync should normally behave)
![image](https://github.com/Namo2/InPlayerEpisodePreview/assets/39034192/cd7eb24a-f513-4655-bbf3-de58ab72f71e)

I made sure it's not the custom CSS I'm using and I've tried disabling all other plugins and made sure that these two are the ones who's conflicting with each other, also I've tried re-installing jellyfin thinking it may solve the issue but it didn't.

**Comment by Druidblack** [comment]
Really. After I managed to get the InPlayerEpisodePreview plugin to work, the menu of the jellyfin-ani-sync plugin stopped working. Although the plugin itself works and syncs the data. I am sending my data to shikimori.

**Comment by Druidblack** [comment]
I had both plugins, but the InPlayerEpisodePreview plugin (the icon did not appear) did not work as needed, but was active. Ani-Sync had all the menus. 
The Ani-Sync plugin is not affected by the plugin itself, but by what it does with the interface.

**Comment by Namo2** [comment]
Hey, is this still an issue?
I just installed the Ani-Sync plugin and couldn't recreate it

**Comment by XDark187** [comment]
> Hey, is this still an issue? I just installed the Ani-Sync plugin and couldn't recreate it

I just checked again and it seems to be solved
