### ISSUE TITLE
[BUG] Do not show boutton on movies

### ISSUE THREAD

**Issue by Gauvino** [Namo2/InPlayerEpisodePreview#24]
On every movies the button is showing, but since it's a movie why showing it?
![chrome_oA9CI8g2UG](https://github.com/user-attachments/assets/ec732411-6452-4981-9e14-9d966fdfafb7)

**Comment by Namo2** [comment]
Hey,

that is a bug I also noticed myself.
I will fix it when i have some more time.

But i plan to implement it for tmdb collections in the future.

Thanks for mentioning this.
