### ISSUE TITLE
InPlayerEpisodePreview  slows the player down to the point of timeout for series with a large number of episode

### ISSUE THREAD

**Issue by HamletDuFromage** [Namo2/InPlayerEpisodePreview#25]
Basically this bug https://github.com/jellyfin/jellyfin-web/issues/5779, but exacerbated (I assume because it has to fetch descriptions, thumbnails etc). I couldn't start any episode of a show with 130 episodes before jellyfin-web would ask me if I wanted to transcode it

I know that this behavior is mentioned here https://github.com/Namo2/InPlayerEpisodePreview?tab=readme-ov-file#drawbacks, however if it can't be fixed, there should be a disclaimer that it will hang the player

It's a shame because it's a truly great plugin, but if jellyfin itself doesn't have an elegant way to address this issue, maybe it can't be done with the existing implementation

**Comment by Namo2** [comment]
Hey, thanks for the info. 
I haven't had any problems so far, not even with larger numbers of episodes, but of course, every system is different.

I don't have that much time at the moment. However, pagination is something I'd like to implement in the future anyway.
I'll have a look at that

**Comment by Namo2** [comment]
Hey, i heavily reduced the data which is loaded by the plugin.
Would be nice if you could try it out and tell me if your problem is solved, because i couldn't recreate it.
