### ISSUE TITLE
[bug] Breaks server discovery

### ISSUE THREAD

**Issue by LeviSnoot** [Namo2/InPlayerEpisodePreview#27]
Started to get reports that people can't reach my Jellyfin instance and after some investigating it looks like this server causes the web client to lose track of where the server is. 

When users go to the domain for the instance they are greeted with

```
No servers have been found using the automatic server discovery

[Add server]
```

Users can click the button and type the same base URL as they're visiting in to access the server again but this isn't intuitive or intended behavior. After digging around in my Nginx config and getting nowhere I tried disabling the last plugin I installed (this one) and everything instantly went back to normal.

**Comment by Namo2** [comment]
Hey, thanks for reporting this issue.

Could you tell me on which clients this error appeared on? (Firefox, Chrome, Windows Client, ...)

**Comment by loof2736** [comment]
I've been getting this as well, it was happening to me on Firefox but I didn't test other browsers

**Comment by loof2736** [comment]
Actually I'm not sure if this is an issue with 10.9.10 or with this plugin, I found the same issue in the main Jellyfin repo here: https://github.com/jellyfin/jellyfin/issues/12523

**Comment by alvitali** [comment]
> Actually I'm not sure if this is an issue with 10.9.10 or with this plugin, I found the same issue in the main Jellyfin repo here: [jellyfin/jellyfin#12523](https://github.com/jellyfin/jellyfin/issues/12523)

I was the one who opened jellyfin/jellyfin#12523, and can confirm the issue was caused by the plugin, not Jellyfin 10.9.10 itself. Would love to see this resolved however, as I quite like the plugin!

On a somewhat unrelated note - are there any plans to integrate the plugin into Jellyfin itself? As the functionality you provide is great :)

**Comment by alvitali** [comment]
@Namo2 I encountered this issue on all browsers I tested (Firefox & Edge on both Windows and macOS, Safari & Chrome on macOS). There is some more information including browser console logs provided by another user in the issue mentioned above

**Comment by Namo2** [comment]
That this error occurs on 10.9.10 is great information. I will try to fix it this weekend.

Since the JMP version is not needed anymore I canceled my plans to integrate it to jellyfin but who knows what the future will bring. The possibility is still there of course but my focus will be on the bugs which are currently still open

**Comment by alvitali** [comment]
> Since the JMP version is not needed anymore I canceled my plans to integrate it to jellyfin but who knows what the future will bring. The possibility is still there of course but my focus will be on the bugs which are currently still open

Jellyfin Media Player (desktop app?) I'd love to see it for jellyfin-web anyways - I'm expecting some of the features of the web client to be implemented in the native apps too (e.g. trickplay preview, skipping segments in the future). Sorry for the thread unrelated to this issue - thanks for giving us this plugin, in any case! <3

**Comment by Namo2** [comment]
> > Since the JMP version is not needed anymore I canceled my plans to integrate it to jellyfin but who knows what the future will bring. The possibility is still there of course but my focus will be on the bugs which are currently still open
> 
> Jellyfin Media Player (desktop app?) I'd love to see it for jellyfin-web anyways - I'm expecting some of the features of the web client to be implemented in the native apps too (e.g. trickplay preview, skipping segments in the future). Sorry for the thread unrelated to this issue - thanks for giving us this plugin, in any case! <3

Hey the issue should be fixed now. Feel free to try it out and tell me if it works.
Btw fyi, the trickplay preview is in the nativ desktop client
