### ISSUE TITLE
Cannot access settings: Failed to get resource

### ISSUE THREAD

**Issue by jstebenne** [Namo2/InPlayerEpisodePreview#3]
I am trying to access the plugin settings, but doing so causes a crash in the web UI. This errors is logged:

```
[ERR] [25] Jellyfin.Api.Controllers.DashboardController: Failed to get resource Namo.Plugin.InPlayerEpisodePreview.Configuration.configPage.html from plugin InPlayerEpisodePreview
```

I just managed to edit the permissions of the web files to be able to inject the plugin's script in it.

**Comment by Namo2** [comment]
Hey,

thanks for reporting this issue.
Currently there are no setting for the plugin itself, so you are not missing out on something.

The problem itself will of course be fixed
