### ISSUE TITLE
Jellyfin on Subpath Doesn't Render Images

### ISSUE THREAD

**Issue by lewisakura** [Namo2/InPlayerEpisodePreview#34]
https://github.com/Namo2/InPlayerEpisodePreview/blob/fdbbed233d13a8a7ca0331505512641757689715/Namo.Plugin.InPlayerEpisodePreview/Web/Components/EpisodeElementTemplate.ts#L63

Because of this line, the plugin tries to fetch the asset from the root path, but because my Jellyfin is on a subpath (`/jellyfin`) this ends up loading nothing.

**Comment by Namo2** [comment]
I will publish a fix this evening. Anything else you noticed not working under a subpath?
