### ISSUE TITLE
plugin button does not appear in the Web Client 

### ISSUE THREAD

**Issue by dirdante2** [Namo2/InPlayerEpisodePreview#5]
i was looking for this function for a long time :D 
sadly the plugin button does not appear in the Web Client 
while the plugin is loading correct
```
Namo.Plugin.InPlayerEpisodePreview.InPlayerEpisodePreviewPlugin: Attempting to inject preview script code in "/jellyfin/jellyfin-web/index.html"
Namo.Plugin.InPlayerEpisodePreview.InPlayerEpisodePreviewPlugin: Finished injecting preview script code in "/jellyfin/jellyfin-web/index.html"
Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "InPlayerEpisodePreview" "1.0.0.0"
```

and i got no error while starting playback.
i use jellyfin in docker: jellyfin/jellyfin:latest
and i deleted the User and group Var in my docker config.

**Comment by Namo2** [comment]
Hey, there is now a new release [v1.0.1.0](https://github.com/Namo2/InPlayerEpisodePreview/releases/tag/v1.0.1.0)

I hope it will resolve your issue. 
If you still have problems with the appearance of the preview button, try the following:
 - Refresh the web page
 - Try to load the show in a different way (e.g. from the start page, the page of the show itself, the episode selection of the show)

**Comment by dirdante2** [comment]
yes its working i can see and interact with the button now
also i can click die plugin in the plugins section (even if it is empty) 

I hope you find a way to start playback via the plugin in the web client
