### ISSUE TITLE
button shows the first season everytime 

### ISSUE THREAD

**Issue by dirdante2** [Namo2/InPlayerEpisodePreview#7]
When you click on the button, the first season is always displayed, even if you are currently watching another season.
If you then click on the correct season, the current episode will be displayed expanded as it should be

**Comment by AbandonedCart** [comment]
After running a few tests, it seems like the value is being checked correctly, but either not set or dropped somewhere. The first season gets the checkmark, too. I would think if it weren't displaying the value correctly, they would all get marked.
